---
kind: pipeline
type: kubernetes
name: cnj-docker-tools-build

steps:
  - name: commit-stage
    image: docker.at41tools.k8s.aws.msgoat.eu/cloudtrain/cnj-drone-build-java8
    privileged: true
    commands:
      - start-docker.sh
      - mvn clean deploy --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false
