pipeline:
  commit-stage:
    image: docker.at.automotive.msg.team/cloudtrain/cnj-drone-mvn-k8s
    commands:
      - mvn clean deploy --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false -Dtest.target.route=http://10.118.17.191:8080
