version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "cloudtrain-codebuild-dockerhub:docker-user"
    DOCKERHUB_PAT: "cloudtrain-codebuild-dockerhub:docker-pat"

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Install docker compose plugin"
      - DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
      - mkdir -p $DOCKER_CONFIG/cli-plugins
      - curl -SL https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
      - chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running phase pre_build"
      - echo "Download common configuration files"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/.mvn/settings.xml /root/.m2/settings.xml
      - echo "Authenticate on DockerHub"
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PAT
      - echo "Check docker version"
      - docker version
      - echo "Check docker-compose version"
      - docker-compose version
      - echo "Check docker compose plugin version"
      - docker compose version
  build:
    on-failure: ABORT
    commands:
      - echo "Running phase build"
      - echo Running commit-stage of the build
      - mvn clean deploy --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false
  post_build:
    commands:
      - echo "Running phase post_build"

cache:
  paths:
    - "/root/.m2/**/*"