version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USER: "cloudtrain-codebuild-dockerhub:docker-user"
    DOCKERHUB_PAT: "cloudtrain-codebuild-dockerhub:docker-pat"

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      docker: 20
  pre_build:
    on-failure: ABORT
    commands:
      - echo "Running phase pre_build"
      - echo "Download common configuration files"
      - aws s3 cp s3://s3-eu-west-1-cloudtrain-codebuild-shared/.mvn/settings.xml /root/.m2/settings.xml
      - echo "Authenticate on DockerHub"
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PAT
      - echo "Check docker version"
      - docker version
      - echo "Check docker-compose version"
      - docker-compose version
      - echo "Check support of docker compose command"
      - docker compose
  build:
    on-failure: ABORT
    commands:
      - echo "Running phase build"
      - echo Running commit-stage of the build
      - mvn clean deploy --batch-mode --fail-fast --errors -V -U -Dsurefire.useFile=false
  post_build:
    commands:
      - echo "Running phase post_build"

cache:
  paths:
    - "/root/.m2/**/*"